name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm run test
      - run: npm run test:e2e
  solidity-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
        working-directory: ./samples/solidity
      - run: npm run compile
        working-directory: ./samples/solidity
      - run: npm run test
        working-directory: ./samples/solidity
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build --tag ghcr.io/hyperledger/firefly-tokens-erc20-erc721 .
